# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Llama3.2 1B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-3.2-1B --output-dir /tmp/Llama-3.2-1B --ignore-patterns "original/consolidated.00.pth"
#
# To launch on 4 devices, run the following command from root:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3_2/1B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3_2/1B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# Single device full finetuning requires more memory optimizations. It's
# best to use 1B_full_single_device.yaml for those cases


output_dir: /sc/projects/sci-aisc/ld/mini/torchtune/llama3_2_1B/full # /tmp may be deleted by your system. Change it to your preference.

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /sc/projects/sci-aisc/ld/mini/Llama-3.2-1B/original/tokenizer.model
  max_seq_len: null

# Dataset and Sampler
dataset:
  firstn_datasets: 0
  data_location: data/more_data_data_batches
  preprocessing_workers: 1
  data_mode: data_batches  # Options: template_batches, data_batches
seed: 42
batch_size: 16

# Validation
run_val_every_n_steps: 2048  # Change to an integer to enable validation every N steps
eval_batches: 0
batch_size_val: 64

# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /sc/projects/sci-aisc/ld/mini/Llama-3.2-1B/
  checkpoint_files: [
    model.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3_2
resume_from_checkpoint: False

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  fused: True
loss:
  _component_: torchtune.modules.loss.LinearCrossEntropyLoss

# Training
epochs: 10
max_steps_per_epoch: null
gradient_accumulation_steps: 4  # Use to increase effective batch size
loss_type: variance
gradient_aggregation_type: mean # only used if data_mode: data_batches 

# Environment
device: cuda
dtype: bf16

# Memory management
enable_activation_checkpointing: True  # True reduces memory
enable_activation_offloading: False  # True reduces memory
clip_grad_norm: null
compile: True  # torch.compile the model + loss, True increases speed + decreases memory
optimizer_in_bwd: False  # True saves memory. Requires gradient_accumulation_steps=1


# Logging
debug: False
offline: False
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  project: mini
  entity: transformersclub
log_every_n_steps: 1
log_peak_memory_stats: True
log_level: INFO  # DEBUG, WARN, etc.


# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1

# Generation params
generation:
  temperature: 0.6 # 0.8 and 0.6 are popular values to try
  top_k: 300
  do_sample: True

sanity_check_generation: False
sanity_check_dataloading: True
